services:
  app:
    depends_on:
      - evolution
      - redis
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - evolution-net
    ports:
      - 3000:3000
      - 5555:5555
    env_file:
      - ./.env
    # volumes:
    #   - ./.:/home/node/app

  evolution:
    image: atendai/evolution-api:latest
    restart: always
    depends_on:
      - redis
      - postgres
    ports:
      - 8080:8080
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution-net
    env_file:
      - ./.env.evolution
    expose:
      - 8080

  redis:
    image: redis:latest
    networks:
      - evolution-net
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - evolution_redis:/data
    ports:
      - 6379:6379

  postgres:
    image: postgres:15
    networks:
      - evolution-net
    command: ["postgres", "-c", "max_connections=1000"]
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=PASSWORD
      - POSTGRES_USER=user
      - POSTGRES_DB=evolution
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432

volumes:
  evolution_instances:
  evolution_redis:
  postgres_data:

networks:
  evolution-net:
    driver: bridge
